export interface Order {
  "id": string,
  "orderId" : string,
  "orderPickupType": string,
  "shipmentType": string,
  "sarokhWarehouseId": string,
  "deliveryPersonName": string,
  "deliveryPersonContact": String,
  "pickupDatetime": string,
  "updatedDatetime": string,
  "shipperWarehouseId": string,
  "shipmentOrderItems": ShipmentOrderItems[],
}
export interface ShipmentOrderItems {
  "trackingNumber": string,
  "shipmentTitle": string,
  "shipmentContent": string,
  "shipmentValue": string,
  "shipmentType": string,
  "paymentType": string,
  "shipmentBilledAmount": string,
  "shipmentDeliveryCharges": string,
  "weight": string,
  "dimensions": string,
  "deliveryStatus": string,
  "shipmentOrderId": string,
  "receiverName": string,
  "contact":string,
  "email": string,
  "address": string,
  "city": string,
  "country": string,
  "postalCode": string,
  "locationLongitude": string,
  "locationLatitude": string
}

